ccr/ccr

.travis.yml, test_h5/tst_h_bzip2.c
now using bzip2 filter in test
=> now using bzip2 filter in test

hdf5_plugins/BZIP2/src/Makefile.am, hdf5_plugins/LZ4/src/H5Zlz4.c, include/ccr_test.h, test_h5/Makefile.am, test_h5/tst_h_lz4.c
=> Added HDF5 test for LZ4 filter

include/ccr.h, src/Makefile.am, src/ccr.c, test/Makefile.am, test/tst_lz4.c, test_h5/Makefile.am
Fixes #1 
Now bzip2 and lz4 are working well. We can examine where to go from here.
=> add support for LZ4

hdf5_plugins/BZIP2/Makefile.am, hdf5_plugins/BZIP2/configure.ac, hdf5_plugins/BZIP2/example/Makefile.am, hdf5_plugins/BZIP2/example/h5ex_d_bzip2.c, hdf5_plugins/BZIP2/src/Makefile.am, hdf5_plugins/LZ4/Makefile.am, hdf5_plugins/LZ4/configure.ac, hdf5_plugins/LZ4/example/Makefile.am, hdf5_plugins/LZ4/example/h5ex_d_lz4.c, hdf5_plugins/LZ4/src/Makefile.am, hdf5_plugins/Makefile.am, hdf5_plugins/configure.ac
=> updated plugins

README.md, configure.ac
=> getting ready for 1.0 release

Makefile.am, configure.ac, fsrc/Makefile.am, fsrc/ccr.F90, ftest/Makefile.am, ftest/ftst_ccr_bzip2.F90, ftest/ftst_ccr_lz4.F90, hdf5_plugins/BZIP2/src/Makefile.am, src/Makefile.am
Fixes #14 
In this PR I add a Fortran API for the bzip2 and lz4 filter functions.
=> Add a fortran API and tests

docs/Doxyfile.in, fsrc/ccr.F90, src/ccr.c
=> adding documentation

hdf5_plugins/BZIP2/Makefile.am, hdf5_plugins/LZ4/Makefile.am, hdf5_plugins/LZ4/example/Makefile.am, hdf5_plugins/LZ4/example/tst_lz4_size.c, include/ccr_test.h, test/tst_lz4.c, test_h5/Makefile.am, test_h5/tst_h_lz4.c, test_h5/tst_lz4_size.c
=> adding some lz4 tests

.github/workflows/c-cpp.yml, README.md, configure.ac, src/Makefile.am, test/Makefile.am
Part of #36 
Fixes #34 
I this PR I add some documentation to the README, and also start adding github testing.
=> improving docs, turned off tests

.travis.yml, README.md, configure.ac, src/ccr.c, test/Makefile.am, test_h5/Makefile.am
Part of #38 
Part of #34 
Part of #30
Now require netcdf-c-4.7.4. Also some doc improvements. Fixed issue with bzip test. Also fixed build issue when LZ4
=> fixed bzip2 test, improved docs, fixed some build issues

ChangeLog, Makefile.am, README.md, configure.ac, fsrc/Makefile.am, fsrc/ccr.F90, ftest/Makefile.am, ftest/ftst_ccr_bitgroom.F90, ftest/ftst_ccr_zstandard.F90, hdf5_plugins/BITGROOM/src/H5Zbitgroom.c, hdf5_plugins/ZSTANDARD/configure.ac, hdf5_plugins/ZSTANDARD/src/H5Zzstandard.c, include/ccr.h, src/ccr.c, test/Makefile.am, test/tst_bitgroom.c, test/tst_bzip2.c, test/tst_lz4.c, test/tst_zstandard.c, test_h5/Makefile.am, test_h5/tst_h_bitgroom.c, test_h5/tst_h_bzip2.c, test_h5/tst_h_lz4.c, test_h5/tst_h_zstandard.c, test_h5/tst_zstandard_size.c
=> Add nc_inq/def_var_bitgroom/zstandard

README.md, configure.ac, src/ccr.c
Part of #38 
Minor fix in configure.ac of --enable-lz4 processing.
Also adding some documentation. (Part of #54).
=> Minor fix of --enable-lz4 code in configure.ac

src/ccr.c
=> Add BitGroom reference to ccr.c

.github/workflows/lz4.yml, ftest/ftst_ccr_bitgroom.F90, ftest/ftst_ccr_bzip2.F90, ftest/ftst_ccr_lz4.F90, ftest/ftst_ccr_zstandard.F90
=> starting to test fortran in CI

test_h5/Makefile.am
If successful will address #50
=> Turn-on HDF5 tests for BitGroom so make check runs them by default

.github/workflows/lz4.yml
Fixes #36
Turning on more tests in CI runs...
=> enable more filter test in CI

hdf5_plugins/BITGROOM/example/Makefile.am, hdf5_plugins/BZIP2/example/Makefile.am, hdf5_plugins/LZ4/example/Makefile.am, hdf5_plugins/ZSTANDARD/example/Makefile.am, src/Makefile.am
Part of #30 
We don't need to link to filters.
=> makefile cleanup

configure.ac, test/Makefile.am, test/run_tests.sh.in, test/tst_perf.c, test/tst_zstandard.c
Part of #84 
Adding a performance test.
=> Starting to test performance of zstandard

configure.ac
=> fix typo that prevents BZIP2 filter from building

hdf5_plugins/ZSTANDARD/src/H5Zzstandard.c, src/ccr.c
This just improves the internal docs in response to #88
=> Update Zstandard clevel documentation

.github/workflows/macos_all.yml, include/ccr_test.h, test/tst_bitgroom.c, test/tst_bzip2.c, test/tst_lz4.c, test/tst_zstandard.c
Fixes #81 
Adding macos testing to CI.
=> adding mac testing in github actions

ccr-config.in, configure.ac
This script begins life as a heavily hacked version of `nc-config` to address #96.
=> Add ccr-config script generated by configure.ac

.github/workflows/build_all.yml, ftest/ftst_ccr_bitgroom.F90, ftest/ftst_ccr_bzip2.F90, ftest/ftst_ccr_zstandard.F90
Part of #101 
Fix memory leak in two of the fortran tests.
=> add deallocation in fortran test

.github/workflows/build_asan.yml, ftest/ftst_ccr_bitgroom.F90
=> trying asan build again

test/tst_perf.c
Part of #84 
More performance test code.
=> more performance testing

.github/workflows/build_par.yml, test/tst_par.c
Part of #106 
Parallel I/O build in support of #85. Merging this to try and get caches working properly...
=> Parallel I/O CI build

configure.ac, test/tst_bitgroom.c, test/tst_zstandard.c
=> added comment, fixed warnings in test code

.github/workflows/build_par.yml, configure.ac, test/Makefile.am, test/run_par_tests.sh.in, test/tst_par.c
Part of #85 
Adding parallel I/O tests. Still some more work to be done in future PRs.
=> parallel tests

configure.ac, hdf5_plugins/Makefile.am, hdf5_plugins/configure.ac, test/Makefile.am, test/run_benchmarks.sh.in, test/tst_eamv1_benchmark.c
Fixes #84 
Part of #33
Renamed test, better documentation.
I added the bitgroom filter. 
Here's some results:
=> renamed benchmark, better documented file

.github/workflows/multifilter.yml, test/run_tests.sh.in, test/tst_perf.c, test/tst_zstandard.c
Fixes #33 
I can't understand why this test does not work.
The same code works fine in tst_eamv1_benchmark.c.
=> Add test of bitgroom + zstandard filter

src/ccr.c
Documentation updates.
Fixes #134 
Fixes #135
=> more bitgroom documentation

README.md
=> added authors

src/ccr.c, test/tst_bzip2.c, test/tst_zstandard.c
Part of #148 
Part of #151
More testing of bitgroom and zstandard.
Also fixed bzip2 inq function for multifilters.
=> more testing of multifilters, fixing nc_inq_bzip2() for multifilters

src/ccr.c, test/tst_bitgroom.c
Fixes #155 
Fixes #153
now bitgroom allows different NSD for float and double, also test with double
=> now bitgroom allows different NSD for float and double, also test with double

.github/workflows/minimal.yml, .github/workflows/minimal_2.yml, .github/workflows/multifilter_asan.yml, src/ccr.c
Fixes #159 
Fixes #158 
Fixes #163 
Fix leak add asan for multifilter testing
=> fix leak add asan for multifilter testing

fsrc/ccr.F90
Just a fix for some spelling mistakes I saw when looking over the docs.
=> Fix spelling error

.github/workflows/macos_all.yml, configure.ac, fsrc/Makefile.am, src/Makefile.am, test/tst_gfs_data_1.c
Fixes #171 
Part of #177
Some fixes for tst_gfs_data_1.c.
Also updated some version numbers for the 1.2.0 release.
=> Some fixes for tst_gfs_data_1.c

configure.ac, test/tst_gfs_data_1.c
=> changed test data

test/tst_gfs_data_1.c
=> fixed pre-processor logic in tst_gfs_data_1.c

hdf5_plugins/BITGROOM/src/H5Zbitgroom.c
=> Do not BG values equal to NC_FILL_FLOAT or NC_FILL_DOUBLE

hdf5_plugins/BITGROOM/src/H5Zbitgroom.c
=> BitGroom NC_FILL_FLOAT or NC_FILL_DOUBLE if _FillValue explicitly defined

hdf5_plugins/BITGROOM/src/H5Zbitgroom.c
=> Refactor BitGrooming to compare to explicit/implicit missing value in same loop

configure.ac, hdf5_plugins/BITGROOM/src/H5Zbitgroom.c, hdf5_plugins/BZIP2/example/run_tests.sh, test/tst_bitgroom.c
=> better printing in bitgroom test

test/Makefile.am, test/tst_compress.c
Fixes #195.
Added performance test code in support of benchmarking for AGU paper.
=> adding new performance test in support of AGU 2021 paper

README.md
=> Add autoreconf -i to build instructions

hdf5_plugins/GRANULARBG/example/h5ex_d_granularbg.c, hdf5_plugins/GRANULARBG/src/H5Zgranularbg.c, include/ccr.h
=> Change GBG ID from self-selected 37373 to HDF-issued 32023

configure.ac
changed version to 1.3.0
@czender I'm about to do the 1.3.0 release. If there's any objection, speak now, or forever hold your peace...
=> changed version to 1.3.0

hdf5_plugins/BITGROOM/src/H5Zbitgroom.c, hdf5_plugins/BITROUND/src/H5Zbitround.c, hdf5_plugins/BITROUND/src/Makefile.am, test/tst_bitgroom.c
=> Correct # of explicit bits in IEEE DP mantissa

README.md, ccr-config.in, configure.ac
=> Implement BitRound codec

.github/workflows/build_all.yml, .github/workflows/build_asan.yml, .github/workflows/build_par.yml, .github/workflows/build_par_2.yml, .github/workflows/lz4.yml, .github/workflows/macos_all.yml, .github/workflows/minimal.yml, .github/workflows/minimal_2.yml
Fixes #218 
changed CI to new netcdf-c tarball location
=> changed CI to new netcdf-c tarball location

.github/workflows/minimal.yml, test/Makefile.am, test_h5/Makefile.am, test_h5/run_tests.sh.in
=> fixed --disable-bzip2

README.md
=> added new references to README
